server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8088 #Nacos服务注册中心地址，这边配置成集群的模式
    sentinel:
      transport:
        dashboard: localhost:8180   #配置Sentinel Dashboard地址
        port: 8719
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            #namespace: ${spring.cloud.nacos.discovery.namespace}
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true                  #激活Sentinel对Feign的支持