server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
#ribbon:
#  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
#  ReadTimeout: 5000
#  #指的是建立连接后从服务器读取到可用资源所用的时间
#  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.hzhiping.service.PaymentFeignService: debug

#region 局部设置OpenFeign超时时间修改配置文件的方式
#feign:
#  client:
#    config:
#      cloud-payment-service:  #服务提供方的名字
#        logger-level: BASIC
#        connect-timeout: 5000 #连接超时的时间，默认为2秒，单位：毫秒
#        read-timeout: 3000    #请求处理超时时间，默认为5秒，单位：毫秒
#        retryer: 2            #重试
#endregion

#region 局部设置OpenFeign超时时间修改配置文件的方式
feign:
  client:
    config:
      cloud-payment-service: #服务提供方的名字
        logger-level: BASIC
        contract: feign.Contract.Default
#endregion